// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20210607223746_ReviewUpdate")]
    partial class ReviewUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RateReview")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CityName = "Vancouver",
                            CountryName = "Canada",
                            RateReview = 5,
                            Review = "I love this destination. There was lots of fun things to do. The landmarks alone are worth the travel!"
                        },
                        new
                        {
                            DestinationId = 2,
                            CityName = "Mexico City",
                            CountryName = "Mexico",
                            RateReview = 4,
                            Review = "Everything was so colorful and the mural art was amazing. Definitely worth the travel to see some of the Aztec ancient sites!"
                        },
                        new
                        {
                            DestinationId = 3,
                            CityName = "Venezuela",
                            CountryName = "Italy",
                            RateReview = 5,
                            Review = "The food is amazing and the ancient buildings and churches are beautiful! There is also lots of art and sculptures to be seen. Make sure you bring a few pairs of walking shoes!"
                        },
                        new
                        {
                            DestinationId = 4,
                            CityName = "Song Khon",
                            CountryName = "Thailand",
                            RateReview = 4,
                            Review = "The weather was nice and warm. The food not only was cheap but also really tasty. Its worth spending money on a good hotel!"
                        },
                        new
                        {
                            DestinationId = 5,
                            CityName = "Auckland",
                            CountryName = "New Zeland",
                            RateReview = 5,
                            Review = "You have to visit for yourself. The food was really good in general. The valleys were breathtaking..."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
